### ISSUE TITLE
Methods to interact with the `search_settings` endpoint 

### ISSUE THREAD

**Issue by JanmanX** [elastic/app-search-python#19]
Hi!

I have created a PR with functions to interact with the `search_settings` endpoint:
https://github.com/elastic/app-search-python/pull/18

/JanmanX

**Comment by JasonStoltz** [comment]
Will check this out shortly, thanks

**Comment by CorrosiveKid** [comment]
Seemed like #18 was closed without being merged. I've redone the work and updated the tests and documentation with #30.

@JasonStoltz Please review when you have some time.

**Comment by JasonStoltz** [comment]
@CorrosiveKid I will take a look today, thanks!
