### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by jsma** [elastic/app-search-python#23]
This link is broken:
```
For more information on keys, check out the [documentation](https://swiftype.com/documentation/app-search/credentials).
```

I believe it should be:
```
For more information on keys, check out the [documentation](https://swiftype.com/documentation/app-search/api/credentials).
```

This link is also broken, but I'm not sure where it should link to:
```
The `host_identifier` can be found within the [Credentials](https://app.swiftype.com/ascredentials) menu.
```

In general, should the README continue to direct people to https://app.swiftype.com/as or should it be updated to direct people to the Elastic Cloud hosted version of App Search? For example, `host_identifier` doesn't appear to be a thing in the Elastic Cloud version so I found these instructions to be a bit confusing.

**Comment by JasonStoltz** [comment]
Thanks for pointing those out. 

Generally speaking, yes, the use of `host_identifier` and linking to the credentials screen should only be done within the https://github.com/elastic/app-search-python#swiftypecom-app-search-users section. It is not relevant to Elastic Cloud. Sorry for the confusion!
