### ISSUE TITLE
Methods to get analytics

### ISSUE THREAD

**Issue by flara-infoxchange** [elastic/app-search-python#33]
Hi, we need to get analytics for a given engine as available on the api https://swiftype.com/documentation/app-search/api/analytics

I have submmited a PR for this functionality:

https://github.com/elastic/app-search-python/pull/32 

Cheers

**Comment by sethmlarson** [comment]
Closing this issue for the same reason given in #32, there are new clients coming for App Search and we're focusing development on those clients.
